on:
  workflow_dispatch:
    inputs:
      task_number:
        description: "ServiceNow Task Number"
        required: true
      short_description:
        description: "Task Description"
        required: true

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "Task number: ${{ github.event.inputs.task_number }}"
          echo "Description: ${{ github.event.inputs.short_description }}"
