on:
  workflow_dispatch:
    inputs:
      change_request_number:
        description: "ServiceNow Task Number"
        required: true
      description:
        description: "Description"
        required: true

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "Change Request number: ${{ github.event.inputs.task_number }}"
          echo "Description: ${{ github.event.inputs.short_description }}"
